CMakeLists.txt: Add Qt5Quick to required dependencies
OE-builds comlained with floods of errors as:

| ld: <...>/recipe-sysroot/usr/lib/libVfLogger.so.0.0.1: undefined reference to `QQuickItem::keyReleaseEvent(QKeyEvent*)'

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>